#Elmar Ólafsson
w = open("Textaskra.txt", "w")
w.write("Lorem Ipsum is simply dummy text of the printing and typesetting industry." + "\n")
w.close()
w = open("Textaskra.txt", "a")
w.write("Lorem Ipsum has been the industry's standard dummy text ever since the 1500s," + "\n")
w.write("when an unknown printer took a galley of type and scrambled it to make a type specimen book." + "\n")
w.write("It has survived not only five centuries." + "\n")
w = open("Textaskra.txt", "r")
w = open("Textaskra.txt", "r")
print(w.readline())
w.close()
